// <auto-generated />
using System;
using HW2_StoreWebApi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HW2_StoreWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240124221724_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HW2_StoreWebApi.Db.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("groups_pk");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("HW2_StoreWebApi.Db.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("products_pk");

                    b.HasIndex("GroupId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("HW2_StoreWebApi.Db.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("stores_pk");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("HW2_StoreWebApi.Db.Storesproduct", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.HasKey("StoreId", "ProductId")
                        .HasName("storesproducts_pk");

                    b.HasIndex("ProductId");

                    b.ToTable("storesproducts", (string)null);
                });

            modelBuilder.Entity("HW2_StoreWebApi.Db.Product", b =>
                {
                    b.HasOne("HW2_StoreWebApi.Db.Group", "Group")
                        .WithMany("Products")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("products_groups_id_fk");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("HW2_StoreWebApi.Db.Storesproduct", b =>
                {
                    b.HasOne("HW2_StoreWebApi.Db.Product", "Product")
                        .WithMany("Storesproducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("storesproducts_products_id_fk");

                    b.HasOne("HW2_StoreWebApi.Db.Store", "Store")
                        .WithMany("Storesproducts")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("storesproducts_stores_id_fk");

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("HW2_StoreWebApi.Db.Group", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HW2_StoreWebApi.Db.Product", b =>
                {
                    b.Navigation("Storesproducts");
                });

            modelBuilder.Entity("HW2_StoreWebApi.Db.Store", b =>
                {
                    b.Navigation("Storesproducts");
                });
#pragma warning restore 612, 618
        }
    }
}
